name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - 'koptan/**'
      - '.github/workflows/Release.yaml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Lint Charts
        run: |
          helm lint koptan

  release:
    needs: lint
    permissions:
      contents: write # Needed to create releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Setup Chart Release Directory
        run: |
          mkdir -p .chart-release
          helm package koptan --destination .chart-release/

      - name: Generate Repository Index
        run: helm repo index .chart-release/ --url https://charts.felukka.org

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: koptan
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .chart-release
          cname: charts.felukka.org
          keep_files: true